### ISSUE TITLE
Host Name should inherit from EC2 Name

### ISSUE THREAD

**Issue by rmgpinto** [hashicorp/boundary-plugin-host-aws#13]
When creating a `boundary_host_set_plugin` resource through terraform, the name appearing on boundary is the ID of the host (ex: `h_1gZVzevKl2`) instead of the EC2 instance name (tag:Name).

**Comment by the-demoss** [comment]
I have written code to use the name tag as the hostname. Can I somehow create a pull request?

**Comment by Anton-Sagurov** [comment]
@jefferai 

> I can't tell if that's a standardized mechanism -- do you know if this is standardized anywhere?
I don't think this is a standard. Is it possible to add check if tag Name or name present - then put it somewhere?

And it would be great - to add the public and private IPs to the output.

I just faced this. I have only 7 hosts in the auto-discovery group, but it's not easy to find the required one:
```$ boundary hosts list -host-catalog-id hc_VwXDVGpceD

Host information:
  ID:                    h_dw6MkwChGe
    External ID:         i-0056ac1d04c9d4334
    Version:             1
    Type:                plugin
    Authorized Actions:
      no-op
      read

  ID:                    h_KOrAfmbdLT
    External ID:         i-08a6970bd37b52f9b
    Version:             1
    Type:                plugin
    Authorized Actions:
      no-op
      read

  ID:                    h_l4WazYimwH
    External ID:         i-05fb216ecc95afcdd
    Version:             1
    Type:                plugin
    Authorized Actions:
      no-op
      read

  ID:                    h_MHmUfd2hEE
    External ID:         i-084d2980f9bb21644
    Version:             1
    Type:                plugin
    Authorized Actions:
      no-op
      read

  ID:                    h_nR9mpDlhHq
    External ID:         i-03d2b1d6ca10abebf
    Version:             1
    Type:                plugin
    Authorized Actions:
      no-op
      read

  ID:                    h_WXBCHKvQ7r
    External ID:         i-09ecfa0d54aa25919
    Version:             1
    Type:                plugin
    Authorized Actions:
      no-op
      read

  ID:                    h_xM8xnioQOf
    External ID:         i-0f16d93acf6d71ec3
    Version:             1
    Type:                plugin
    Authorized Actions:
      no-op
      read
```

For example, I will have 100 hosts - what is the intended way to find the required one?

**Comment by matheusmgon** [comment]
Have any updates?
Is hard to know which is the ec2's on Boundary using this plugin.
It will be better if we can see the ec2 the hostname/name on the list of machines

**Comment by jefferai** [comment]
No updates currently, but I've raised this to our product team.

**Comment by jefferai** [comment]
I do want to note that the external ID is unlikely to change to the name -- it's the unique ID from the cloud and we want to surface that. I think the more likely outcome is we surface some other select information as well. I do want to get this addressed though.

**Comment by matheusmgon** [comment]
Maybe it will be better if we can set it into the host-set to get the tag Name or the hostname machine.
I understand the identification is based on a unique id, but to our,  and probably also your clients is very hard to know "what this machine is that by the id identification".

**Comment by jefferai** [comment]
I understand your concern, I'm simply saying that rather than change what's there we're more likely to add to what's there. So as a possibility, along with External ID, we'd return External Name and maybe External Tags.

**Comment by PPacent** [comment]
@matheusmgon , @rmgpinto thank you for the suggestions. This suggestion is very similar to the more broad one [here](https://github.com/hashicorp/boundary/issues/1821) to more closely align dynamic host resource names in Boundary with the linked resources on the catalog's external provider. This is something the team is actively tracking and paying close attention to. 

I am going to close this request as a duplicate and suggest folks upvote [this issue](https://github.com/hashicorp/boundary/issues/1821) if you think aligning host names with EC2 instance names (or more generally, aligning dynamic host resource names in Boundary with their external equivalents) is something you'd like the team to invest in. Thanks!

**Comment by PPacent** [comment]
@matheusmgon , @rmgpinto thank you for the suggestions. This suggestion is very similar to the more broad one https://github.com/hashicorp/boundary/issues/1821 to more closely align dynamic host resource names in Boundary with the linked resources on the catalog's external provider. This is something the team is actively tracking and paying close attention to.

I am going to close this request as a duplicate and suggest folks upvote https://github.com/hashicorp/boundary/issues/1821 if you think aligning host names with EC2 instance names (or more generally, aligning dynamic host resource names in Boundary with their external equivalents) is something you'd like the team to invest in. Thanks!
